/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeLib_NativeLib */

#ifndef _Included_nativeLib_NativeLib
#define _Included_nativeLib_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeLib_NativeLib
 * Method:    trierParCrashs
 * Signature: ([Lmodel/Avion;)[Lmodel/Avion;
 */
JNIEXPORT jobjectArray JNICALL Java_nativeLib_NativeLib_trierParCrashs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nativeLib_NativeLib
 * Method:    trierParAutonomie
 * Signature: ([Lmodel/Avion;)[Lmodel/Avion;
 */
JNIEXPORT jobjectArray JNICALL Java_nativeLib_NativeLib_trierParAutonomie
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nativeLib_NativeLib
 * Method:    moyenneCrashs
 * Signature: ([Lmodel/Avion;)D
 */
JNIEXPORT jdouble JNICALL Java_nativeLib_NativeLib_moyenneCrashs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     nativeLib_NativeLib
 * Method:    moyenneAutonomie
 * Signature: ([Lmodel/Avion;)D
 */
JNIEXPORT jdouble JNICALL Java_nativeLib_NativeLib_moyenneAutonomie
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
